### ISSUE TITLE
[feature request] Show the count of reviews along with the avg score

### ISSUE THREAD

**Issue by dalerka** [angusmcleod/discourse-ratings#11]
Would it be possible to add the total number (count) of reviews along with the score (in parenthesis) to show a more informative "rating" like: 

:star: :star: :star: :star: :star: (5 / 1) where "4" = score and "1"= total number of reviews per topic.

**Comment by angusmcleod** [comment]
Added in: https://github.com/angusmcleod/discourse-ratings/commit/0822e094a5fa25d875c615fcc07a1bbd02676d06

**Comment by hosnas** [comment]
I didn't understand what does it exactly mean in first glance. I mean I saw 4.9/11 and for a minute I was thinking what the heck is going on? 
I think it would be better to represent this in another way like google way : 
![screenshot-2017-12-17 - google search](https://user-images.githubusercontent.com/26921196/34075052-a0a3dda0-e2d0-11e7-9388-8c5a39c82ee0.png)

or by adding an emoji beside it like  4.5 - 219 :man:

**Comment by dalerka** [comment]
I think Amazon (with their great data and team) got this right: 
![image](https://user-images.githubusercontent.com/3251602/34077291-2f690280-e322-11e7-90b3-a7a3bb1e59eb.png)

People tend to hate "fractions" since school :) 
Stars give a clear idea of an "overall" score as long as I can see how many people voted. 
Plus, hover/tap can reveal expanded info (rough % is nice, like in "polls", only show fraction if less than 10% per level, i.e. _0.4%_ but _10%_). 

I'm against extra icons/emojis though and no need for the "star" word at _"1 star"..."5 star"_ marks, just _"1"..."5"_ is good. Also, I prefer simple _"Score: 4.7"_ instead of _"4.7 out of 5 stars"_. 

Sure, styling can be better :)

**Comment by angusmcleod** [comment]
Resolved. See further:
https://meta.discourse.org/t/topic-ratings-plugin/39578/128
