### ISSUE TITLE
hide 'No ratings yet' under the topic title when no rating

### ISSUE THREAD

**Issue by livc** [angusmcleod/discourse-ratings#14]
Hi,

I saw you were working on this feature from <https://meta.discourse.org/t/topic-ratings-plugin/39578/168?u=livc>, but I don't see this option in setting. Thanks!

**Comment by angusmcleod** [comment]
Hey! Could you make this a feature request here? Thanks :)

https://discourse.angusmcleod.com.au/w/feature-request

**Comment by livc** [comment]
ok :)
