### ISSUE TITLE
Suggestion: no rating for the first post

### ISSUE THREAD

**Issue by 13bzhang** [angusmcleod/discourse-ratings#3]
Your plug-in is great and I really enjoyed using it. My team is building a site called [Science Commons](http://discourse.sciencecommons.site/) where academics can discuss research papers. Each topic is about a single paper; the first post is a "wiki" that contains a summary of the paper. I would like to use your rating plug-in for Science Commons. But my concern is that when I turn on the rating tag, I am forced to give a rating on the first post. Is there a way such that no rating is required for the first post? I want to be an impartial admin who posts the paper and don't want to give my own opinion about the paper.

**Comment by angusmcleod** [comment]
Hey @13bzhang thanks for the feedback! There isn't a way to prevent the first post from having a rating at the moment, but I'll add it as a setting soon for your use case.

ref: https://meta.discourse.org/t/topic-ratings-plugin/39578/37?u=angus

**Comment by angusmcleod** [comment]
Hey @13bzhang I just added a feature that allows a user to not add a rating to a post in a ratings topic, and to remove an existing rating they gave from a ratings topic. More details here: https://meta.discourse.org/t/topic-ratings-plugin/39578/38?u=angus

**Comment by 13bzhang** [comment]
Thank you for working on this!
