### ISSUE TITLE
plugin.rb

### ISSUE THREAD

**Issue by Alavi1412** [angusmcleod/discourse-ratings#6]
Hi angus.
can you describe plugin.rb codes?
I am beginner at plugin coding and most of the codes you have wrote is confusing for me.(I know ruby)

**Comment by Alavi1412** [comment]
for start:
can explain this:
```
Category.register_custom_field_type('rating_enabled', :boolean)

  module ::DiscourseRatings
    class Engine < ::Rails::Engine
      engine_name "discourse_ratings"
      isolate_namespace DiscourseRatings
    end
  end
```

**Comment by angusmcleod** [comment]
@Alavi1412 Hey. Sure.

> Category.register_custom_field_type('rating_enabled', :boolean)

This is a method for the Category class that sets the type of a custom field. Custom fields are types of data stores you can use in plugins to associate data with core models in Discourse like Categories, Topics and Users. There are [3 types you can set](https://github.com/discourse/discourse/blob/master/app/models/concerns/has_custom_fields.rb#L34): boolean, integer and json. If you don't set a type the field will be a string.

>   module ::DiscourseRatings
       class Engine < ::Rails::Engine
         engine_name "discourse_ratings"
         isolate_namespace DiscourseRatings
       end
     end

**Comment by Alavi1412** [comment]
thank you.
I have a questions:
1.Category or Topic or ... are classes and need to be defined. Where are these classes defined?
and can you explain this class?
```
require_dependency "application_controller"
  class DiscourseRatings::RatingController < ::ApplicationController
    def rate
      post = Post.find(params[:id].to_i)
      post.custom_fields["rating"] = params[:rating].to_i
      post.custom_fields["rating_weight"] = 1
      post.save!

      average = RatingsHelper.calculate_topic_average(post.topic)
      RatingsHelper.push_ratings_to_clients(post.topic, average, post.id)
      render json: success_json
    end

    def weight
      post = Post.with_deleted.find(params[:id].to_i)
      post.custom_fields["rating_weight"] = params[:weight].to_i
      post.save!

      average = RatingsHelper.calculate_topic_average(post.topic)
      RatingsHelper.push_ratings_to_clients(post.topic, average, post.id)
      render json: success_json
    end

    def remove
      id = params[:id].to_i
      post = Post.find(id)
      PostCustomField.destroy_all(post_id: id, name:"rating")
      PostCustomField.destroy_all(post_id: id, name:"rating_weight")

      average = RatingsHelper.calculate_topic_average(post.topic)
      RatingsHelper.push_ratings_to_clients(post.topic, average, post.id)
      render json: success_json
    end
  end
```

**Comment by Alavi1412** [comment]
@angusmcleod 
I just want to find each topics and categories followers or watchers or trackers numbers.
How can I do it?
